<ul class="emoji-list">
    <li>😀</li>
    <li>😁</li>
    <li>😂</li>
    <li>🤣</li>
    <li>😃</li>
    <li>😄</li>
    <li>😅</li>
    <li>😆</li>
    <li>😉</li>
    <li>😊</li>
    <li>😋</li>
    <li>😎</li>
    <li>😍</li>
    <li>😘</li>
    <li>😗</li>
    <li>😙</li>
    <li>😚</li>
    <li>☺</li>
    <li>🙂</li>
    <li>🤗</li>
    <li>🤩</li>
    <li>🤔</li>
    <li>🤨</li>
    <li>😐</li>
    <li>😑</li>
    <li>😶</li>
    <li>🙄</li>
    <li>😏</li>
    <li>😣</li>
    <li>😥</li>
    <li>😮</li>
    <li>🤐</li>
    <li>😯</li>
    <li>😪</li>
    <li>😫</li>
    <li>😴</li>
    <li>😌</li>
    <li>😛</li>
    <li>😜</li>
    <li>😝</li>
    <li>🤤</li>
    <li>😒</li>
    <li>😓</li>
    <li>😔</li>
    <li>😕</li>
    <li>🙃</li>
    <li>🤑</li>
    <li>😲</li>
    <li>☹</li>
    <li>🙁</li>
    <li>😖</li>
    <li>😞</li>
    <li>😟</li>
    <li>😤</li>
    <li>😢</li>
    <li>😭</li>
    <li>😦</li>
    <li>😧</li>
    <li>😨</li>
    <li>😩</li>
    <li>🤯</li>
    <li>😬</li>
    <li>😰</li>
    <li>😱</li>
    <li>😳</li>
    <li>🤪</li>
    <li>😵</li>
    <li>😡</li>
    <li>😠</li>
    <li>🤬</li>
    <li>😷</li>
    <li>🤒</li>
    <li>🤕</li>
    <li>🤢</li>
    <li>🤮</li>
    <li>🤧</li>
    <li>😇</li>
    <li>🤠</li>
    <li>🤡</li>
    <li>🤥</li>
    <li>🤫</li>
    <li>🤭</li>
    <li>🧐</li>
    <li>🤓</li>
    <li>😈</li>
    <li>👿</li>
    <li>👹</li>
    <li>👺</li>
    <li>💀</li>
    <li>👻</li>
    <li>👽</li>
    <li>🤖</li>
    <li>💩</li>
    <li>😺</li>
    <li>😸</li>
    <li>😹</li>
    <li>😻</li>
    <li>😼</li>
    <li>😽</li>
    <li>🙀</li>
    <li>😿</li>
    <li>😾</li>
    <li>🤳</li>
    <li>💪</li>
    <li>👈</li>
    <li>👉</li>
    <li>☝</li>
    <li>👆</li>
    <li>🖕</li>
    <li>👇</li>
    <li>✌</li>
    <li>🤞</li>
    <li>🖖</li>
    <li>🤘</li>
    <li>🖐</li>
    <li>✋</li>
    <li>👌</li>
    <li>👍</li>
    <li>👎</li>
    <li>✊</li>
    <li>👊</li>
    <li>🤛</li>
    <li>🤚</li>
    <li>👋</li>
    <li>🤟</li>
    <li>✍</li>
    <li>👏</li>
    <li>👐</li>
    <li>🙌</li>
    <li>🤲</li>
    <li>🙏</li>
    <li>🤝</li>
    <li>💅</li>
    <li>👂</li>
    <li>👃</li>
    <li>👣</li>
    <li>👀</li>
    <li>👁</li>
    <li>🧠</li>
    <li>👅</li>
    <li>👄</li>
    <li>💋</li>
    <li>👓</li>
    <li>🕶</li>
    <li>👔</li>
    <li>👕</li>
    <li>👖</li>
    <li>🧣</li>
    <li>🧤</li>
    <li>🧥</li>
    <li>🧦</li>
    <li>👗</li>
    <li>👘</li>
    <li>👙</li>
    <li>👚</li>
    <li>👛</li>
    <li>👜</li>
    <li>👝</li>
    <li>🎒</li>
    <li>👞</li>
    <li>👟</li>
    <li>👠</li>
    <li>👡</li>
    <li>👢</li>
    <li>👑</li>
    <li>👒</li>
    <li>🎩</li>
    <li>🎓</li>
    <li>🧢</li>
    <li>⛑</li>
    <li>💄</li>
    <li>💍</li>
    <li>🌂</li>
    <li>☂</li>
    <li>💼</li>
</ul>